import { useEffect, useState } from 'react';
import { RouterProvider, useLocation } from '../router-shim';
import { AuthProvider, useAuth } from './contexts/AuthContext';
import { LanguageProvider, useLanguage } from './contexts/LanguageContext';
import { checkBackendHealth } from './lib/api';
import LandingPage from './pages/public/LandingPage'; import LoginPage from './pages/public/LoginPage'; import RegisterPage from './pages/public/RegisterPage';
import Dashboard from './pages/user/Dashboard'; import ProfilePage from './pages/user/ProfilePage'; import DiseaseDetectionPage from './pages/user/DiseaseDetectionPage'; import ChatbotPage from './pages/user/ChatbotPage'; import WeatherPage from './pages/user/WeatherPage'; import MarketPricePage from './pages/user/MarketPricePage'; import FertilizerPage from './pages/user/FertilizerPage'; import HistoryPage from './pages/user/HistoryPage';
import AdminDashboard from './pages/admin/AdminDashboard'; import UserManagement from './pages/admin/UserManagement'; import MarketPriceUpdate from './pages/admin/MarketPriceUpdate';

const protectedPaths = ['/dashboard', '/profile', '/disease-detection', '/chatbot', '/weather', '/market-prices', '/fertilizer', '/history', '/admin', '/admin/users', '/admin/market-prices'];
function BackendGate({ children }: { children: React.ReactNode }) { const { t } = useLanguage(); const [ready, setReady] = useState(false); const [checking, setChecking] = useState(true); useEffect(() => { let active = true; const verify = async () => { try { await checkBackendHealth(); if (active) { setReady(true); setChecking(false); } } catch { if (active) { setReady(false); setChecking(false); } } }; void verify(); const id = window.setInterval(verify, 5000); return () => { active = false; window.clearInterval(id); }; }, []); if (checking || !ready) return <div className="flex min-h-screen items-center justify-center bg-green-50 px-4"><div className="w-full max-w-lg rounded-2xl border bg-white p-8 text-center shadow-lg"><p className="font-semibold text-green-700">{t('appTitle')}</p><h1 className="mt-4 text-3xl font-bold">{checking ? t('backendChecking') : t('backendUnavailable')}</h1><p className="mt-3 text-gray-600">{t('backendHelp')}</p></div></div>; return <>{children}</>; }
function ProtectedPage({ children, adminOnly = false }: { children: React.ReactNode; adminOnly?: boolean }) { const { isAuthenticated, isLoading, user } = useAuth(); const { t } = useLanguage(); if (isLoading) return <div className="flex min-h-screen items-center justify-center bg-green-50 text-green-700">{t('loading')}</div>; if (!isAuthenticated) return <LoginPage />; if (adminOnly && user?.role !== 'admin') return <Dashboard />; return <>{children}</>; }
function Pages() { const { pathname } = useLocation(); const routes: Record<string, React.ReactNode> = { '/': <LandingPage />, '/login': <LoginPage />, '/register': <RegisterPage />, '/dashboard': <ProtectedPage><Dashboard /></ProtectedPage>, '/profile': <ProtectedPage><ProfilePage /></ProtectedPage>, '/disease-detection': <ProtectedPage><DiseaseDetectionPage /></ProtectedPage>, '/chatbot': <ProtectedPage><ChatbotPage /></ProtectedPage>, '/weather': <ProtectedPage><WeatherPage /></ProtectedPage>, '/market-prices': <ProtectedPage><MarketPricePage /></ProtectedPage>, '/fertilizer': <ProtectedPage><FertilizerPage /></ProtectedPage>, '/history': <ProtectedPage><HistoryPage /></ProtectedPage>, '/admin': <ProtectedPage adminOnly><AdminDashboard /></ProtectedPage>, '/admin/users': <ProtectedPage adminOnly><UserManagement /></ProtectedPage>, '/admin/market-prices': <ProtectedPage adminOnly><MarketPriceUpdate /></ProtectedPage> }; return <>{routes[pathname] ?? (protectedPaths.includes(pathname) ? <ProtectedPage><Dashboard /></ProtectedPage> : <LandingPage />)}</>; }
export default function App() { return <LanguageProvider><BackendGate><RouterProvider><AuthProvider><Pages /></AuthProvider></RouterProvider></BackendGate></LanguageProvider>; }
