# Generated by Django 5.2.14 on 2026-06-28 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('suggestion', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to='disease_detection.diseasehistory')),
            ],
            options={
                'db_table': 'fertilizer_recommendations',
                'ordering': ['-date'],
            },
        ),
    ]
